name: 'check-version-number'
description: 'Action to run workflowr on analysis scripts.'
author: 'Josh Schoenbachler'
inputs:
  package_string:
    description: 'String containing package information in format NAME---DRAT_VERSION---CRAN_VERSION'
    required: true
  github_token:
    description: 'Token to be used for drat repo.'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Split package_string
      id: split-string
      run: |
        PACKAGE_NAME=$(echo ${{ inputs.package_string }} | awk 'BEGIN {FS="---" } ; { print $1 }')
        echo "::set-output name=PACKAGE_NAME::$PACKAGE_NAME"
        DRAT_VERSION=$(echo ${{ inputs.package_string }} | awk 'BEGIN {FS="---" } ; { print $2 }')
        echo "::set-output name=DRAT_VERSION::$DRAT_VERSION"
        CRAN_VERSION=$(echo ${{ inputs.package_string }} | awk 'BEGIN {FS="---" } ; { print $3 }')
        echo "::set-output name=CRAN_VERSION::$CRAN_VERSION"
      shell: bash

    - name: Create an issue
      uses: JasonEtco/create-an-issue@v2
      env: 
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PACKAGE_NAME: ${{ steps.split-string.outputs.PACKAGE_NAME }}
        DRAT_VERSION: ${{ steps.split-string.outputs.DRAT_VERSION }}
        CRAN_VERSION: ${{ steps.split-string.outputs.CRAN_VERSION }}


    