name: 'R-CMD-check'
description: 'Action to run R CMD check on a matrix of operating systems.'
author: 'Josh Schoenbachler'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: r-lib/actions/setup-pandoc@v2

    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.config.r }}
        http-user-agent: ${{ matrix.config.http-user-agent }}
        use-public-rspm: true

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: rcmdcheck

    - name: Setup environment Mac
      if: ${{ matrix.config.os == 'macOS-latest' }}
      run: |
        wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/3.0.0/sratoolkit.3.0.0-mac64.tar.gz
        tar -zxvf sratoolkit.3.0.0-mac64.tar.gz
        echo 'export PATH="${PATH}:${HOME}/sratoolkit.3.0.0-mac64/bin"' >> ~/.bashrc
        echo 'export PATH="${PATH}:${HOME}/sratoolkit.3.0.0-mac64/bin"' >> ~/.profile
        rm sratoolkit*.tar.gz

        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        sh Miniconda3-latest-MacOSX-x86_64.sh -b -p ~/miniconda3
        rm Miniconda3-latest-MacOSX-x86_64.sh
        ~/miniconda3/bin/conda init bash

        source ~/miniconda3/etc/profile.d/conda.sh
        conda config --set auto_activate_base false
        conda activate

        conda config --add channels defaults
        conda config --add channels bioconda
        conda config --add channels conda-forge

        conda install mamba -c conda-forge

        mamba install fastq-screen fastqc multiqc pigz refgenie salmon trim-galore

        mkdir -p ~/genomes
        refgenie init -c ~/genomes/genome_config.yaml
        echo 'export REFGENIE="${HOME}/genomes/genome_config.yaml"' >> ${GITHUB_ENV}

        refgenie pull mm10/salmon_partial_sa_index --genome-config ~/genomes/genome_config.yaml

      shell: bash

    - name: Setup environment Ubuntu
      if: ${{ matrix.config.os == 'ubuntu-latest' }}
      run: |
        wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/3.0.0/sratoolkit.3.0.0-ubuntu64.tar.gz
        tar -zxvf sratoolkit.3.0.0-ubuntu64.tar.gz
        echo 'export PATH="${PATH}:${HOME}/sratoolkit.3.0.0-ubuntu64/bin"' >> ~/.bashrc
        echo 'export PATH="${PATH}:${HOME}/sratoolkit.3.0.0-ubuntu64/bin"' >> ~/.profile
        rm sratoolkit*.tar.gz

        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        sh Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda3
        rm Miniconda3-latest-Linux-x86_64.sh
        ~/miniconda3/bin/conda init bash

        source ~/miniconda3/etc/profile.d/conda.sh
        conda config --set auto_activate_base false
        conda activate

        conda config --add channels defaults
        conda config --add channels bioconda
        conda config --add channels conda-forge

        conda install mamba -c conda-forge
        mamba install refgenie trim-galore fastqc fastq-screen salmon multiqc

        mkdir -p ~/genomes
        refgenie init -c ~/genomes/genome_config.yaml
        echo 'export REFGENIE="${HOME}/genomes/genome_config.yaml"' >> ${GITHUB_ENV}

        refgenie pull mm10/salmon_partial_sa_index --genome-config ~/genomes/genome_config.yaml
      shell: bash

    - uses: r-lib/actions/check-r-package@v2

    - name: Show testthat output
      run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
      shell: bash