name: 'R-CMD-check'
description: 'Action to run R CMD check on a matrix of operating systems.'
author: 'Josh Schoenbachler'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: r-lib/actions/setup-pandoc@v1

    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: ${{ matrix.config.r }}
        http-user-agent: ${{ matrix.config.http-user-agent }}
        use-public-rspm: true

    - uses: r-lib/actions/setup-r-dependencies@v1
      with:
        extra-packages: rcmdcheck

    - name: Setup environment Mac
      if: ${{ matrix.config.os == 'macOS-latest' }}
      run: |
        mkdir ~/Applications
        wget https://download.asperasoft.com/download/sw/connect/3.8.0/IBMAsperaConnectInstallerSystemWide-3.8.0.158555.dmg
        sudo hdiutil attach IBMAsperaConnectInstallerSystemWide-3.8.0.158555.dmg
        sudo installer -package '/Volumes/Aspera Connect Installer/IBMAsperaConnectInstallerSystemWide.pkg' -target ~/Applications
        sudo hdiutil unmount '/Volumes/Aspera Connect Installer'

        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        sh Miniconda3-latest-MacOSX-x86_64.sh -b -p ~/miniconda3
        rm Miniconda3-latest-MacOSX-x86_64.sh
        ~/miniconda3/bin/conda init bash

        source ~/miniconda3/etc/profile.d/conda.sh
        conda config --set auto_activate_base false
        conda activate

        conda config --add channels defaults
        conda config --add channels bioconda
        conda config --add channels conda-forge

        conda install mamba -c conda-forge

        mamba install refgenie trim-galore fastqc fastq-screen salmon multiqc

        mkdir -p ~/genomes
        refgenie init -c ~/genomes/genome_config.yaml
        echo 'export REFGENIE="${HOME}/genomes/genome_config.yaml"' >> ${GITHUB_ENV}

        refgenie pull mm10/salmon_partial_sa_index --genome-config ~/genomes/genome_config.yaml

      shell: bash

    - name: Setup environment Linux
      if: ${{ matrix.config.os == 'ubuntu-latest' }}
      run: |
        wget https://d3gcli72yxqn2z.cloudfront.net/connect_latest/v4/bin/ibm-aspera-connect_4.1.0.46-linux_x86_64.tar.gz
        tar -zxvf ibm-aspera-connect_4.1.0.46-linux_x86_64.tar.gz
        ./ibm-aspera-connect_4.1.0.46-linux_x86_64.sh
        rm ibm-aspera-connect*

        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        sh Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda3
        rm Miniconda3-latest-Linux-x86_64.sh
        ~/miniconda3/bin/conda init bash

        source ~/miniconda3/etc/profile.d/conda.sh
        conda config --set auto_activate_base false
        conda activate

        conda config --add channels defaults
        conda config --add channels bioconda
        conda config --add channels conda-forge

        conda install mamba -c conda-forge
        mamba install refgenie trim-galore fastqc fastq-screen salmon multiqc

        mkdir -p ~/genomes
        refgenie init -c ~/genomes/genome_config.yaml
        echo 'export REFGENIE="${HOME}/genomes/genome_config.yaml"' >> ${GITHUB_ENV}
        

        refgenie pull mm10/salmon_partial_sa_index --genome-config ~/genomes/genome_config.yaml
      shell: bash

    - uses: r-lib/actions/check-r-package@v1

    - name: Show testthat output
      run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
      shell: bash