name: 'R-CMD-check'
description: 'Action to run R CMD check on a matrix of operating systems.'
author: 'Josh Schoenbachler'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: r-lib/actions/setup-pandoc@v2

    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.config.r }}
        http-user-agent: ${{ matrix.config.http-user-agent }}
        use-public-rspm: true

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: rcmdcheck

    - name: Install SRA Toolkit Mac
      if: ${{ matrix.config.os == 'macOS-latest'}}
      run: |
        wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/3.0.0/sratoolkit.3.0.0-mac64.tar.gz
        tar -zxvf sratoolkit.3.0.0-mac64.tar.gz
        echo 'export PATH="${PATH}:${HOME}/sratoolkit.3.0.0-mac64/bin"' >> ~/.bashrc
        echo 'export PATH="${PATH}:${HOME}/sratoolkit.3.0.0-mac64/bin"' >> ~/.profile
        rm sratoolkit*.tar.gz
      shell: Rscript {0}

    - name: Install SRA Toolkit Linux
      if: ${{ matrix.config.os == 'ubuntu-latest' }}
      run: |
        wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/3.0.0/sratoolkit.3.0.0-ubuntu64.tar.gz
        tar -zxvf sratoolkit.3.0.0-ubuntu64.tar.gz
        echo 'export PATH="${PATH}:${HOME}/sratoolkit.3.0.0-ubuntu64/bin"' >> ~/.bashrc
        echo 'export PATH="${PATH}:${HOME}/sratoolkit.3.0.0-ubuntu64/bin"' >> ~/.profile
        rm sratoolkit*.tar.gz
      shell: bash

    - name: Setup environment
      if: ${{ matrix.config.os == 'macOS-latest' || matrix.config.os == 'ubuntu-latest' }}
      run: |
        install.packages('devtools')
        devtools::install(upgrade = 'always')
        seeker:::installTools(sraToolkitPath = NULL, salmonIndexes = 'mm10/salmon_partial_sa_index')
      shell: Rscript {0}

    - uses: r-lib/actions/check-r-package@v2

    - name: Show testthat output
      run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
      shell: bash