name: 'R-CMD-check'
description: 'Action to run R CMD check on a matrix of operating systems.'
author: 'Josh Schoenbachler'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: r-lib/actions/setup-pandoc@v1

    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: ${{ matrix.config.r }}
        http-user-agent: ${{ matrix.config.http-user-agent }}
        use-public-rspm: true

    - uses: r-lib/actions/setup-r-dependencies@v1
      with:
        extra-packages: rcmdcheck

    - name: Check
      env:
        _R_CHECK_CRAN_INCOMING_: false
      run: |
        options(crayon.enabled = TRUE)
        rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), build_args = c("--no-build-vignettes"), error_on = "error", check_dir = "check")
      shell: Rscript {0}

    - name: Show testthat output
      run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
      shell: bash