name: 'analysis-workflowr'
description: 'Action to run workflowr on analysis scripts.'
author: 'Josh Schoenbachler'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: r-lib/actions/setup-pandoc@v1

    - uses: r-lib/actions/setup-r@v1
      with:
        use-public-rspm: true

    - name: Install dependencies to avoid trying to build package
      run: |
        install.packages(c("devtools", "workflowr"))
        devtools::install_dev_deps()
      shell: Rscript {0}

    - name: Switch git branch
      run: |
        git pull
        git switch "gh-pages"
      shell: bash

    - name: Build and publish
      run: |
        workflowr::wflow_build()
        workflowr::wflow_publish()
      shell: Rscript {0}

    - name: Commit to "gh-pages"
      run: |
        git config --local user.name "$GITHUB_ACTOR"
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git commit -m "Updated workflowr site via GitHub Actions"
        git push
      shell: bash