name: 'analysis-workflowr'
description: 'Action to run workflowr on analysis scripts.'
author: 'Josh Schoenbachler'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: r-lib/actions/setup-pandoc@v2

    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - uses: r-lib/actions/setup-r-dependencies@v2

    - name: Switch git branch
      run: |
        git config --local user.name "$GITHUB_ACTOR"
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
      shell: bash

    - name: Build and publish
      run: |
        install.packages("workflowr", repos = "http://cran.us.r-project.org")
        workflowr::wflow_git_config()
        workflowr::wflow_build()
        fileNames = paste0("analysis/", list.files("analysis")[grepl("*.Rmd", list.files("analysis"))])
        workflowr::wflow_publish(republish = TRUE)
        # workflowr::wflow_git_push(branch = "gh-pages", username = "GitHubActions")
      shell: Rscript {0}

    - name: Commit to "gh-pages"
      run: |
        # git add analysis/
        # git add code/
        # git add docs/
        # git add DESCRIPTION
        # git commit -m "Updated workflowr site via GitHub Actions"
        git push -f origin master:gh-pages
      shell: bash