name: 'lint-package'
description: 'Action to run lint for matching lab style guide.'
author: 'Josh Schoenbachler'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Run lint on the package
      run: |
        install.packages('lintr')
        install.packages('data.table')
        source(file.path('.github', 'workflows', 'custom-lint-script.R'))
        print(lfDt)

        if (nrow(lfDt) > 0) stop('Found styling errors.')
      shell: Rscript {0}