# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on: push

name: cran-check

jobs:
  check_version_number:
    runs-on: ubuntu-latest
    name: Check version numbers of packages
    outputs:
        matrix: ${{ steps.matrix.get_packages.value }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: hugheylab/actions/check-version-number@main
        id: get_packages


  create_issue:
    needs: check_version_number
    runs-on: ubuntu-latest
    name: Create issue for packages
    permissions:
      contents: read
      issues: write
    strategy:
      matrix:
        value: ${{fromJson(needs.check_version_number.outputs.matrix)}}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: hugheylab/actions/create-issue@main
        with:
          package_string: ${{ matrix.value }}
