# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on: push

name: check-deploy

jobs:
  lint-package:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.JAKEJH_PAT }}
    steps:
      - uses: hugheylab/actions/lint-package@main
