name: 'test-coverage'
description: 'Action to run tests and upload to codecov.'
author: 'Josh Schoenbachler'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: covr

    - name: Test coverage
      run: covr::codecov()
      shell: Rscript {0}
