name: 'test-coverage'
description: 'Action to run tests and upload to codecov.'
author: 'Josh Schoenbachler'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: r-lib/actions/setup-r@v1
      with:
        use-public-rspm: true

    - uses: r-lib/actions/setup-r-dependencies@v1
      with:
        extra-packages: covr

    - name: Download update for blas issue
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libxt6
        git clone https://github.com/bmbolstad/preprocessCore.git
        cd preprocessCore/
        R CMD INSTALL --configure-args="--disable-threading" .
        cd ../
        rm -rf preprocessCore
      shell: bash

    - name: Install CDF packages for vignettes
      run: |
        source("R/metapredict_utils.R")
        installCustomCdfPackages(c("hgu95av2hsentrezgcdf", "hgu133plus2hsentrezgcdf"))
      shell: Rscript {0}

    - name: Download vignette folder
      run: |
        cd vignettes
        wget "https://www.dropbox.com/s/gdrbmn38261dsy7/expression_data.tar.gz?dl=1"
        mv expression_data.tar.gz?dl=1 expression_data.tar.gz
        tar -xf expression_data.tar.gz
        rm expression_data.tar.gz
        cd ../
      shell: bash

    - name: Test coverage
      run: covr::codecov()
      shell: Rscript {0}